export const GET_SIDENAV = "GET_SIDENAV";
export const GET_SIDENAV_SUCCESS = "GET_SIDENAV_SUCCESS";
export const GET_SIDENAV_FAILED = "GET_SIDENAV_FAILED";
export const SELECT_ELEMENT_SIDENAV = "SELECT_ELEMENT_SIDENAV";
