export const SEND_SMS = "SEND_SMS";
export const SEND_SMS_SUCCESS = "SEND_SMS_SUCCESS";
export const SEND_SMS_FAILED = "SEND_SMS_FAILED";

export const GET_MESSAGES = "GET_MESSAGES";
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";
export const GET_MESSAGES_FAILED = "GET_MESSAGES_FAILED";

export const GET_NUMBERS = "GET_NUMBERS";
export const GET_NUMBERS_SUCCESS = "GET_NUMBERS_SUCCESS";
export const GET_NUMBERS_FAILED = "GET_NUMBERS_FAILED";

export const CLOSE_CREATED = "CLOSE_CREATED";
