export const GET_USER = "GET_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILED = "GET_USER_FAILED";

export const GET_MYACCOUNT = "GET_MYACCOUNT";
export const GET_MYACCOUNT_SUCCESS = "GET_MYACCOUNT_SUCCESS";
export const GET_MYACCOUNT_FAILED = "GET_MYACCOUNT_FAILED";

export const UPDATE_MYACCOUNT = "UPDATE_MYACCOUNT";
export const UPDATE_MYACCOUNT_SUCCESS = "UPDATE_MYACCOUNT_SUCCESS";
export const UPDATE_MYACCOUNT_FAILED = "UPDATE_MYACCOUNT_FAILED";
